name: Build and deploy container app to Azure Web App - nexusTeste

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Login no Azure com o Publish Profile
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nexusTeste'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_527a27165053425a9a461e0170abf219 }}
        images: 'DOCKERFILE-CONTEXT'
        dockerfile: './Dockerfile'
